version: "3.7"
services:

  cran-search:
    build: .
    restart: always
    ports:
      - 8080:8080
      - 5005:5005
    depends_on:
      - mongo
    networks:
      - backend
    environment:
      spring.data.mongodb.host: mongo
      spring.data.mongodb.port: 27017


  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
    networks:
      - backend

volumes:
  db-data:

networks:
  backend: